# Generated by Django 4.1.7 on 2023-04-02 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flightSchool',
            new_name='flightschool',
        ),
    ]
