# Generated by Django 4.1.7 on 2023-04-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightschool',
            name='location',
            field=models.CharField(default='France', max_length=200),
            preserve_default=False,
        ),
    ]
