# Generated by Django 4.1.7 on 2023-04-03 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_account_alter_booking_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='flightschool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.flightschool'),
        ),
    ]
